import "../scss/style.scss";
//import "./swiper";
import "./pricesSwiper";
import "./servicesSwiper";
import "./brandsSwiper";
import "./openCloseBurgerMenu";
import "./openCloseFeedback";
import "./openCloseFeedbackCall";
import "./openCloseSercices";
console.log("Works!");
